-- MySQL Script generated by MySQL Workbench
-- Mon Mar  9 20:22:24 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema newsforreal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema newsforreal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `newsforreal` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `newsforreal` ;

-- -----------------------------------------------------
-- Table `newsforreal`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `newsforreal`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `newsforreal`.`administrator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `newsforreal`.`administrator` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `newsforreal`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `newsforreal`.`comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL,
  `administrator_id` INT NULL,
  `content` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comments_user_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_comments_administrator1_idx` (`administrator_id` ASC) VISIBLE,
  CONSTRAINT `fk_comments_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `newsforreal`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_administrator1`
    FOREIGN KEY (`administrator_id`)
    REFERENCES `newsforreal`.`administrator` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `newsforreal`.`news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `newsforreal`.`news` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `administrator_id` INT NOT NULL,
  `comments_id` INT NULL,
  `title` VARCHAR(45) NOT NULL,
  `category` VARCHAR(45) NULL,
  `date_added` DATETIME NULL,
  `content` LONGTEXT NULL,
  `short_description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_news_comments1_idx` (`comments_id` ASC) VISIBLE,
  INDEX `fk_news_administrator1_idx` (`administrator_id` ASC) VISIBLE,
  CONSTRAINT `fk_news_comments1`
    FOREIGN KEY (`comments_id`)
    REFERENCES `newsforreal`.`comments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_news_administrator1`
    FOREIGN KEY (`administrator_id`)
    REFERENCES `newsforreal`.`administrator` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;