-- MySQL Script generated by MySQL Workbench
-- Fri Feb 28 15:45:38 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema news-assignment
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema news-assignment
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `news-assignment` DEFAULT CHARACTER SET utf8 ;
USE `news-assignment` ;

-- -----------------------------------------------------
-- Table `news-assignment`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `news-assignment`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` LONGTEXT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `news-assignment`.`administrator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `news-assignment`.`administrator` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` LONGTEXT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `news-assignment`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `news-assignment`.`comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `administrator_id` INT NOT NULL,
  `content` TEXT NULL,
  PRIMARY KEY (`id`, `user_id`, `administrator_id`),
  INDEX `fk_komentari_korisnik_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_komentari_administrator1_idx` (`administrator_id` ASC) VISIBLE,
  CONSTRAINT `fk_comments_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `news-assignment`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_administrator`
    FOREIGN KEY (`administrator_id`)
    REFERENCES `news-assignment`.`administrator` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `news-assignment`.`news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `news-assignment`.`news` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `administrator_id` INT NOT NULL,
  `comments_id` INT NOT NULL,
  `comments_user_id` INT NOT NULL,
  `commentsi_administrator_id` INT NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `category` VARCHAR(45) NULL,
  `date_added` DATETIME NULL,
  `content` LONGTEXT NULL,
  `short_description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `administrator_id`, `comments_id`),
  INDEX `fk_vesti_administrator1_idx` (`administrator_id` ASC) VISIBLE,
  INDEX `fk_vesti_komentari1_idx` (`comments_id` ASC, `comments_user_id` ASC, `commentsi_administrator_id` ASC) VISIBLE,
  CONSTRAINT `fk_vesti_administrator1`
    FOREIGN KEY (`administrator_id`)
    REFERENCES `news-assignment`.`administrator` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vesti_komentari1`
    FOREIGN KEY (`comments_id` , `comments_user_id` , `commentsi_administrator_id`)
    REFERENCES `news-assignment`.`comments` (`id` , `user_id` , `administrator_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
